FROM maven:3.9-amazoncorretto-21 AS builder

WORKDIR /app

COPY pom.xml ./
RUN mvn dependency:go-offline

COPY src/ ./src/
RUN mvn clean package -DskipTests

FROM amazoncorretto:21-alpine-jdk

WORKDIR /app
COPY --from=builder /app/target/demo-0.0.1-SNAPSHOT.jar /app/demo.jar

EXPOSE 3000

CMD ["java", "-jar", "demo.jar"]